### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by bruh552** [JSsixtyfour/smashremix#1]
i load the game and it gets to the n64 logo starting part then just stays at a black screen. I followed all the steps perfectly any idea?

**Comment by samuelmaddock** [comment]
To fix the black screen on startup, you must configure Smash Remix's memory size from 4MB to 8MB in the options.

![Project64_2019-11-04_19-40-01MzUH](https://user-images.githubusercontent.com/1656324/68169665-06939780-ff3b-11e9-9eca-b4166fdaf279.png)
