### ISSUE TITLE
A version of this rom hack, but only with unplayable stuff being playable

### ISSUE THREAD

**Issue by Machow8** [JSsixtyfour/smashremix#100]
Hello,

This isn't, really, an issue, but yes a different request:

I hope someday someone create a variation of this rom hack in a way that all unplayable stuff (like: characters: metal mario, master hand, giant dk, all porygon ; stages: battlefield, final destination, metal cavern and beta stages) are available for play.

Like how they already are in actual Smash Remix, but without the new added stuff (like characters, stages, mods and etc).

I believe that with just few tweaks i'm able to inject that variation into wiiu n64 vc, since smash remix, sadly, doesn't work when injected.

Thanks.

**Comment by leodexe** [comment]
You mean like, requesting a **lite** version of the mod? It won't work, I also already tried with Better CSS which is the exact same size as the original Smash Bros (for whatever reason the game crashes on VS menu. It only worked with a very early version of 19XXTE and at this point N64 emulation on the Wii has improved so I should recommend you to emulate it on Wii64/Not64 instead. Plus the Wii U has a more powerful processor than the Wii so I'm pretty sure it should be even more stable than the Wii itself.
