### ISSUE TITLE
Download for .zip file says "needs authorization"

### ISSUE THREAD

**Issue by Blueturtle1999** [JSsixtyfour/smashremix#106]
I tried to download the file many times but it says fhe same thing over and over, is there a way to fix this?

**Comment by jtl3d** [comment]
Sounds like an issue with your computer

**Comment by jtl3d** [comment]
Then we've identified the issue

**Comment by Blueturtle1999** [comment]
> Then we've identified the issue

Huh?

**Comment by Blueturtle1999** [comment]
> Whatever device you are using is locked down to the point that you don't have permissions to do what you want. We can't help with that.

Im using a mobile phone
