### ISSUE TITLE
1P Mode Difficulty Bug

### ISSUE THREAD

**Issue by JonWick34** [JSsixtyfour/smashremix#108]
About halfway through the 1P Remix mode, the difficulty will take a huge spike and turn into Hard or Very Hard mode regardless of the difficulty you chose (characters will be nearly impossible to launch and will read your inputs as if they were on Very Hard mode, hardly even giving you a chance to breathe). This was tested on both Easy mode and Normal mode.

**Comment by JSsixtyfour** [comment]
Remix 1p is harder than the original 1p
