### ISSUE TITLE
Smashketball Stage changed in v1.1.0

### ISSUE THREAD

**Issue by camomagic** [JSsixtyfour/smashremix#109]
The downward facing stationary barrels on each side of the stage have disappeared and the hoops appear lowered. There also may be an issue with the scoreboard being too low as well.

**Comment by JSsixtyfour** [comment]
You turned off hazards accidentally

**Comment by camomagic** [comment]
You're absolutely. I'm glad that is a toggle. Thank you for your hard work. Sorry for the idiocy.
