### ISSUE TITLE
Missing features and upgrades needed to achieve the ultimate mod

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#11]
This mod is great and so far has added so many stages and a expanded CSS for adding future custom characters in the future but it lacks a lot of features that could make it even better, since these features already exists in other mods, I suggest adding them to your mod to improve it

For example, tehzz's SSB64 Better CSS (Link: https://github.com/tehzz/SSB64-Better-CSS ) features playable Metal Mario and Giant Donkey Kong, and, the less relevant, but playable polygons variants of the original 12 cast. These two guys could be a great addition to the mix, at least for me Metal Mario is one of my fav characters.
 
On the other hand, we have jordan's 19XX ( https://github.com/jordanbarkley/19XX ), which is the biggest mod that has ever existed for SSB64, includes a lot of useful features for standard and competitive play, like enhanced AI's, combo meters, neutral starting spawns (Dream Land Only) hitbox display, random/custom music and salty runback, and a lot of useful toggles, just to name a few.

Unarguably, adding these features to Smash Remix will only make it better and I'm looking forward for your mod, excellent work.

**Comment by JSsixtyfour** [comment]
Thanks for your kind words
