### ISSUE TITLE
Feature Suggestion: C Stick Mapping & Tap Jump Toggling

### ISSUE THREAD

**Issue by Kikasuru** [JSsixtyfour/smashremix#110]
Yo!  I just played the new 1.1.0 update, and I'm planning on netplaying it with a couple of friends later, and I will say to keep up the good work!  This mod has been amazing so far and honestly might be my favorite mod for any game ever, it's that great!

I do have a suggestion though, since I'm a bit more accustomed to newer Smash titles, is there a way you could add C Stick Mapping in the character select screen?  It'd be amazing if you could pull out tilts with the C Stick since not everyone (ESPECIALLY myself, I end up throwing out smash attacks instead) is good at throwing out tilts reliably.  It'd also be cool if you could disable Tap Jump and maybe even move it to a shoulder button since C Stick Mapping will hypothetically be a thing.

**Comment by mrj1m0thy** [comment]
For those looking for a tap jump toggle:
https://github.com/mrj1m0thy/smashremix/releases/tag/v2.0.1_tapjump
