### ISSUE TITLE
will ever be a Linux 32bit support ?

### ISSUE THREAD

**Issue by Rutcha** [JSsixtyfour/smashremix#121]
Before anything, Thank you very much for your work! I can't wait to play this Remix, after watching it so much on youtube.

How hard is it to support Linux 32bits ? 

I can't get past "smashremix1.1.1/.ezpatch/bin/linux/ucon64" because it's a "ELF 64-bit LSB executable, x86-64, version 1 (SYSV) "

I know I could use wine and the windows version (and that's my first plan), but I've booted in a non-wine compatible kernel, as I did not select CONFIG_VMSPLIT_1G . So now I'll have to reboot as soon I finish some tasks.
I also know I could use qemu, more precisely just "QEMU User space emulator" and emulate only this executable, but I usually have to go look for a few missing libraries as well.
I also know there are not many linuxes running 32bit and I may end up asking a colleague at work, but I was curious after facing this difficulty. Also don't bother much because my machine may be too slow to run it anyway.

I wish you all well

**Comment by jtl3d** [comment]
We don't work on emulators, so this question is better asked on an emulator's forum. Good luck!

**Comment by Rutcha** [comment]
I'm sorry! It's not about emulation, nor emulator.
It's about patching! Pathing an image. But ok, never mind

**Comment by jtl3d** [comment]
My mistake then. But https://smash64.online now has a patcher so hopefully you can utilize that.
