### ISSUE TITLE
how do you download z64 file?

### ISSUE THREAD

**Issue by greatestgameplayer** [JSsixtyfour/smashremix#123]

**Comment by greatestgameplayer** [comment]
idk how some one pls tell me

**Comment by philiporlando** [comment]
@greatestgameplayer, are you asking us how to download the original SSB64 ROM? If so, we cannot help you. You must legally obtain your own ROM. smashremix does not endorse or condone piracy. Do not ask how to obtain a ROM here.

**Comment by leodexe** [comment]
The patcher wil only work in .z64 format, if you need to convert into .z64 you can use Tool64 to convert your .n64 and .v64 backups.

**Comment by leodexe** [comment]
The patcher wil only work in .z64 format, if you need to convert into .z64 you can use Tool64

**Comment by Unounited** [comment]
downloading the zip file should come with a patcher, xdelta, go here on how to use it: http://sheesh.us/tutorials/how-to-manually-patch-your-rom-using-an-xdelta-file/.
