### ISSUE TITLE
Where can I learn to mod N64 games?

### ISSUE THREAD

**Issue by luisfer-madona** [JSsixtyfour/smashremix#124]
Hi, I will graduate next year in system engineering and I am very curious on learn how to make mods like this, on my favorite console the _N64_.. may i ask you were I can start learning to develop these kind of mods? 
 Which software, and/or language its used? **keep the good work friends!**

**Comment by JSsixtyfour** [comment]
Some info can be found here: http://n64vault.wikidot.com/wiki:super-smash-bros-64 and people on the Smash Remix discord can assist.
