### ISSUE TITLE
Turning off music dosen't work

### ISSUE THREAD

**Issue by 6dyfer** [JSsixtyfour/smashremix#126]
1. It does not work (at least for ' starring wario ! ')

**Comment by 6dyfer** [comment]
At least on kitchen island

**Comment by JSsixtyfour** [comment]
The setting you changed is only for random music. So you need to turn random music on, then in that circumstance, starring wario wouldn't play. It does not prevent a song from being played in other circumstances, such as it being one of the 3 random songs played when selecting a stage normally.
