### ISSUE TITLE
Random Error on Multiplayer

### ISSUE THREAD

**Issue by opiter09** [JSsixtyfour/smashremix#128]
![7CF57A24-71DF-4973-8627-827FE977A2F6](https://user-images.githubusercontent.com/92452568/182502654-b077701a-6495-4d36-98a0-ee55b2200a76.jpeg

**Comment by opiter09** [comment]
On Wii64 emulator on Wii, Rice Graphics edition

**Comment by leodexe** [comment]
Does it crash on Not64 glN64 Graphics edition?

**Comment by JSsixtyfour** [comment]
Our team does not design for compatibility with the wii or wiiU
