### ISSUE TITLE
1P Remix Freeze on Giant Mewtwo

### ISSUE THREAD

**Issue by ryanfbailey** [JSsixtyfour/smashremix#132]
Was playing through 1P remix yesterday and it was running perfectly as always.  Unfortunately when I got to Giant Mewtwo the game froze and never progressed.  I will try it again and see if I can replicate the issue.

Playing As: Fox
Version: v1.2.0
Hardware: NTSC N64 + OME Expansion Pak + Everdrive 64 X7
Controller (Probably doesnt matter): OME Controller + Rumble Pak

Thanks again for the awesome work!

**Comment by goombapatrol** [comment]
Thanks for letting us know! Do you remember if you had any extra settings on? (Practice mode etc) And were you using Port 1?

If you get the crash again, see if you can get the debugger up so we can have more info to work off. [Steps listed here](https://docs.google.com/forms/d/e/1FAIpQLSdvRfr35shW_BpTbPqYYP3lvx6pH5eVIzsar5XhjX1vmyKGqw/viewform)

```
In game, trigger the crash and pull up the SSB crash debugger up with this combo button combo:
Z + R + L
D-Up + C-Up
A + D-Left
B + D-Right
D-Down + C-Down

Take a photo of each screen (cycle through them with Z + L + R).```

**Comment by goombapatrol** [comment]
Okay it looks like an issue with Saffron DL (that was the stage, correct?) thanks for report.
