### ISSUE TITLE
Feature Request: Air Dodging, directional.

### ISSUE THREAD

**Issue by mirddes** [JSsixtyfour/smashremix#137]
just like melee please

**Comment by AnonN10** [comment]
why don't you go play melee instead

**Comment by mirddes** [comment]
Because melee isn't on n64?

**Comment by AnonN10** [comment]
you can emulate it, but alright, if you are using a console it's more complicated I guess

**Comment by mirddes** [comment]
I just reckon with remix already being such a groundbreaking improvement
over the original, it makes sense to inch closer towards melee.

**Comment by AnonN10** [comment]
Yes.

**Comment by Infinitefrgfrags** [comment]
Would you update this feature's?:

1.remake sonic moveset just like in ultimate.

2.added more characters just like team sonic, Pokémon trainer, goku, naruto and more characters!

3.added ultra sonic as a secret playable characters.

Final feature is added a map creator! This feature allows you to make your own map!


Please update this feature's!
