### ISSUE TITLE
Sonic Yellow (no super sonic) bug crash

### ISSUE THREAD

**Issue by alexochoa20** [JSsixtyfour/smashremix#141]
1.3.0 SMASH REMIX, when you change to the yellow color of the normal sonic in the menu where you choose the character, it gives a crash to the game, just that color. Hoping you can give an small update to it to not wait till the next big update. It is happening since the 1.2.0 version :(

**Comment by jtl3d** [comment]
What emulator and gfx plugin? We can't reproduce this.

**Comment by alexochoa20** [comment]
> What emulator and gfx plugin? We can't reproduce this.

I use the Nintendo Switch Online with this game installed (by hack), using the meta data of the original game, but this is the only bug I've found, I don't know if this emulator is something u can work on it, but this is the one I use hehe
