### ISSUE TITLE
Game Keeps Freezing

### ISSUE THREAD

**Issue by Birdy18** [JSsixtyfour/smashremix#143]
I'm running this game on M64Plus FZ on my Kindle and through this, ive been able to play the other versions of Smash Remix without issue.

However for some reason whenever I go into a mode like Training Mode, the game just FREEZES for no reason.  The ROM I use operates perfectly so it's not that and I've never had this issue before with the other versions.

The emulator is up to date so I think there might be something wrong here.  Could someone please help me???

**Comment by Abro61209** [comment]
Having the same issues with Mupen and Parallel on retroarch on my steam deck. Previous versions run flawlessly.

**Comment by Yusfpro** [comment]
Same goes to me

**Comment by JSsixtyfour** [comment]
We design for the console, it may not work on every type of hardware or emulator.
