### ISSUE TITLE
There is an issue with the single player mode when having allies.

### ISSUE THREAD

**Issue by Agent-Kallus** [JSsixtyfour/smashremix#144]
In the Single Player modes, both Vanilla and Remix, when getting to the stages where I have allies against the Duo Teams and against the Giant, they are vulnerable to Friendly Fire and I end up killing them which ends up getting me killed shortly thereafter.

Is there a setting that I need to toggle to stop this from happening or is the game bugged? I brought this up on GBATemp in the topic that was made announcing the arrival of Smash Remix 1.3.0 and it has been ignored.

**Comment by Agent-Kallus** [comment]
That's all fine and dandy, but how do I turn it off? If I want more challenge, I'll play on Very Hard with 1 life like I used to do with DK back in the day.

**Comment by JSsixtyfour** [comment]
That is intended for Remix mode for more challenge, can't be turned off
