### ISSUE TITLE
Issue with Marina Kirby

### ISSUE THREAD

**Issue by blumushrum** [JSsixtyfour/smashremix#145]
game freeze when kirby has the copy ability and uses the air version of the move's down input.

**Comment by blumushrum** [comment]
it happens in training mode with the "show action" toggle.

**Comment by UltyT** [comment]
Same thing happens for me too on console. Only except for me it screws up so bad that it doesn't even show the debugger.

**Comment by JSsixtyfour** [comment]
Fixed in latest release.
