### ISSUE TITLE
King Dedede graphical glitch when using neutral special with hitbox model displays

### ISSUE THREAD

**Issue by philiporlando** [JSsixtyfour/smashremix#147]
I'm seeing some [graphical glitches](https://discord.com/channels/577655757726810112/589569739492294672/1072281159586820106) when using King Dedede's neutral special in training mode. It occurs when using the hitbox model displays (both Hitbox and Hitbox+). So far, I've tested this on Dreamland, Saffron City, and Frosty Village. 

I'm running Smash Remix 1.3.0 on Ubuntu 22.04 via mupen64plus and the OpenGL Video Plugin by Rice (v2.5.0). Please let me know if you need any additional details. Thanks for sharing this awesome project!

**Comment by jtl3d** [comment]
Does it happen with other video plugins? Does it happen always or under certain conditions?

**Comment by philiporlando** [comment]
It happens every time I use neutral special when the Hitbox or Hitbox+ model displays are selected. The extent of the effect seems to slightly vary by stage. I will try testing with another graphics plugin and report back.

**Comment by philiporlando** [comment]
I'm not seeing this issue occur when using the `mupenplus-video-glide64mk2` graphics plugin. I'm unable to test the `mupenplus-video-z64` plugin with my current hardware. 

It looks like it may be plugin/hardware related?

**Comment by JSsixtyfour** [comment]
Seems hardware or software related. Don't think there's anything we can do.
