### ISSUE TITLE
Gave this a try and came across this while messing around. (Console)

### ISSUE THREAD

**Issue by auraspgit** [JSsixtyfour/smashremix#148]
https://www.youtube.com/watch?v=IaOL1SpX4O8

This was recorded from console. The capture software (OBS) was lagging at the beginning. What happened is a few seconds before the end of the video. When you knock a player into the top blast zone on that stage and whenever it's a star finish, that happens. The character is not visible. Not sure if this is intended.

**Comment by leodexe** [comment]
Does this happen in 1vs1 matches on that map as well?

**Comment by Absoluc4s** [comment]
Yeah. I just checked.

**Comment by auraspgit** [comment]
I can confirm that the issue has been fixed in v1.4.0. Thanks!
