### ISSUE TITLE
Roy

### ISSUE THREAD

**Issue by KilQer** [JSsixtyfour/smashremix#151]
Had Roy to smash remix now!!!

It would be a good addition because we need another character fire emblem in this game.

**Comment by ultracodez** [comment]
@JSsixtyfour this is a good addition! How difficult do you think this would be, and is there any way we can help you?

**Comment by ultracodez** [comment]
@JSsixtyfour, why did you close this? 

On another note, can we have the link to the Discord so we can suggest there?

**Comment by JSsixtyfour** [comment]
We don't take character requests.
