### ISSUE TITLE
Suggestion: Add option to customize CPU teching patterns in training mode

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#153]
Just as the title says, there should be some options in regard to the CPU teching behavior in training mode:

Option 1:
Tech Rate: The odds of the CPU will perform a successful tech, anywhere between 0-100%. Setting this value to 0 will always force missed techs, thus disabling all tech directions.

Option 2 method 1: One option for all tech directions
Tech Direction: If set to non-random, as long as Tech Rate isn't 0%, the CPU will always attempt tech in the same direction, otherwise the CPU will just tech at random directions.
If set to random, this method covers all tech directions (forward, backwards, in place)

Option 2 method 2: One option for each tech direction
Tech In Place Rate : Set to 0 to disable tech-in-place.
Tech Forward Rate : Set to 0 to disable forward techs.
Tech Backward Rate : Set to 0 to disable backward techs.
If all options have the same value, they should have the same likelihood of happening, if all options are 0, they are all disabled.

**Comment by Infinitefrgfrags** [comment]
Can you add one more characters? Yeah just add tails prower and one more thing i need. Can you change team battle character colour into original colour, if you want to play your character at the same time, just add shadow and light colour to the opponent! Pls! Your game will be popular than other smash fan-made!

**Comment by leodexe** [comment]
I'm not the developer. You should create your own issue/pull request if you have a suggestion instead of posting on other user's issues.

**Comment by jtl3d** [comment]
CPU tech options added. Thanks for the suggestion!
