### ISSUE TITLE
Sonic Bug (Nintendo Switch Online Emulator)

### ISSUE THREAD

**Issue by alexochoa20** [JSsixtyfour/smashremix#157]
As you can read in the title, I installed Smash Bros Remix as a custom rom (with the original metadata that the program ask to run the game on the emulator) and it runs perfectly with every character, even after the update where you added Sonic... but I realized that.. by changing sonic colors... and reaching the Classic style of this character.. forward or towards provokes a crash in game.. this is the only character that cause this issue, any other character can change everything normally, Slippy and Peppy are perfect.. the problem of sonic is still there since 1.3.0 and now on 1.4.0, any idea what I can do? I use CAVE manager install the game, I'll be help you to fix by testing it, if you want to try.... I also want to teach people how to use the game on switch.. but I wanted to do it till it get fix this problem ... my discord "alezhunk". Thanks for everything! I enjoy the game a lot and I appreciate everything you've been doing. My best desires!

**Comment by JSsixtyfour** [comment]
Appreciate the report but we limit our testing to standard emulators and original hardware. Unfortunately the switch is outside of our scope.
