### ISSUE TITLE
Reopening issue #3 (black textures in Wii) for updating purposes.

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#16]
Reopening this issue for updating purposes.
![IMG_20200316_173612826](https://user-images.githubusercontent.com/24327014/76802259-b6acc300-67ad-11ea-85d1-00fc3d896f78.jpg)

After testing Smash Remix 0.9.2 within Not64 version 2019-04-10 (N64 Emulator for Wii), just found out that the New Stages perfectly loads their custom textures, but not only that, also some already existing stages that on previous SR 0.9.1 couldn't load any textures at all just like OP stated, now load succesfully. After checking the changelist, I thing I found the reason for this. Most, if not all of the stages that were revised for tournament legal conditions, improved framerate, textures, graphics, etc are the ones that actually loads properly, while the others that weren't optimized still load full black textures.

So the devs **unintentionally** FULLY fixed the black texture glitch for these stages:
- Kitchen Island (already fully functional in current SR 0.9.2)

- Glacial River (already fully functional in current SR 0.9.2)
![IMG_20200316_173226330](https://user-images.githubusercontent.com/24327014/76804650-3721f280-67b3-11ea-8aba-f2c5488348e1.jpg)

- Ganon's Tower (revised)
- Dr. Mario (revised)
- Deku Tree (revised)
- Mad Monster Mansion (revised)
- Kalos Pokémon League (revised)
- Pokémon Stadium (revised)
- Smashville (revised)
- Great Bay (revised)
- Fountain of Dreams (revised)
- Tower of Heaven (revised)
- Big Blue (revised)
- Onett (revised)

- Corneria (98% of the textures load, except these two)
<img width="631" alt="corneria98" src="https://user-images.githubusercontent.com/24327014/76803901-4bfd8680-67b1-11ea-884e-9ec838d83d18.png">

These other lists of stages PARTIALLY loads textures. With partially being 50% or much less in most cases upper platforms load and the main stage is entirely all black, like Spiral Mountain:

- Zebes Landing (Alternate music added: Norfair)
![IMG_20200316_172946428](https://user-images.githubusercontent.com/24327014/76804751-74868000-67b3-11ea-8797-a41f218af49d.jpg)

- Corneria City (Alternate music added: Star Wolf)
- Peach castle II (Alternate music added: Wing Cap, Metal Cap)
- Spiral Mountain (??)
- Cool Cool Mountain (Top platforms are now slippery)
- Mementos
- Skyloft (Alternate music added: Gerudo Valley)

Finally, these set of stages, even they share the same textures of the original stages already existing in the game, like Mushroom Kingdom, BF MR and Omega MR don't load at all for whatever reason:

- Mushroom Kingdom BF
![IMG_20200316_173136358](https://user-images.githubusercontent.com/24327014/76804835-aa2b6900-67b3-11ea-8463-a4725d096dc2.jpg)

- Mushroom Kingdom Omega
- First Destination
- Showdown

It may have something to do with the "Character Lighting improvements to most stages", even thought I don't know what that means, but if the stages were fixed unintentionally, then the solution should be there somewhere. I hope this update gives you a clue of how to fix the other black textured stages, if you're ever interested in fixing it since you guys already did that unintentionally.

_Originally posted by @leodexe in https://github.com/JSsixtyfour/smashremix/issues/3#issuecomment-599788705_

**Comment by fancythedeveloper** [comment]
Not64 is kinda old anyways, just use a VC inject and it might work better.

**Comment by leodexe** [comment]
> Not64 is kinda old anyways, just use a VC inject and it might work better.

You didn't even read the whole thing haven't you?
In the original issue I stated that is technically IMPOSSIBLE to inject this ROM because not even the largest WADs can fit the ROM due to it surpassing the maximum size (+40mb). So injecting is ruled out.

Second, Not64 isn't outdated, last year received an update on 2019 November. It is also the only way you can play Smash Remix on a modded Wii.

**Comment by leodexe** [comment]
This issue was closed and I had no answer whatsoever. At least I would expect an answer from a dev that read all the whole stuff and is aware of the issue.

**Comment by jordanbarkley** [comment]
Addressed in #22

**Comment by leodexe** [comment]
Thank you. But #3 , which is the issue I am describing, and #22 are different issues. Here the thing is about black textures on Not64, in #22 that issue describes compatibility with VC Injection, which is technically impossible to "fix". However, as I described this issue here, fixing black textures on Not64 is far easier than trying to make the ROM Hack compatible with VC Injection. Just to point that out. But your answer implies you actually are aware of this and know the difference so pointing this out isn't necessary. But just in case you haven't. Once again thanks for answering. Keep up the good work.

**Comment by leodexe** [comment]
It is worth mentioning that since Smash Remix Lucas Release 0.9.3 four already existing custom stages now displays properly on Not64:
Bowser Stadium
Corneria City
Mute City
Mementos

Also EVERY SINGLE NEW custom stage added in this release also displays properly in Not64, isn't it wonderful? @jordanbarkley
