### ISSUE TITLE
Salty Runback Input Choice for IGR modded N64s?

### ISSUE THREAD

**Issue by JorgeHawkins** [JSsixtyfour/smashremix#163]
This is more of a suggestion rather than a bug.

But some game streamers and hobbyists have their N64s modded with an IGR (in game reset) input. It normally comes with Tim Worthington's RGB mod for the console. The input is `A + B + Z + R + Start`.

This is the same input used in Smash Remix for a Salty Runback. Inputting a SR will instead reset the entire console.

Would it be possible to add multiple options on how to execute a SR? It would also help make the incidences of ragequitting on competitions harder or even make EASIER salty runback inputs for professional players testing live commands outside the training mode.

I personally would appreciate the choice of inputs. :)

**Comment by jtl3d** [comment]
Thanks for the suggestion - hope the implementation works for you!

**Comment by JorgeHawkins** [comment]
Thank you so much for taking my idea into consideration, it really meant a lot.

If I can make a suggestion over its implementation, the command `A + B + Z + R + DPad Right` messes up with music when Keep Music after Salty Runbacks is enabled, as `DPad Right` is also used for choosing a stage song, so the previous song gets reset after the salty runback. As both `DPad Left` and `DPad Up` are not currently in use, maybe either of those could be a choice instead?
