### ISSUE TITLE
Bosses in Remix 1P seem too hard in Very Easy & Easy

### ISSUE THREAD

**Issue by ChronoMoogle** [JSsixtyfour/smashremix#171]
They've got quite a strong difficulty spike compared to all other fights in the low difficulties, so I think it might be worth it to tweak them a little bit for beginners.

**Comment by Calinou** [comment]
It seems 1.5.1 [addresses](https://github.com/JSsixtyfour/smashremix/releases/tag/1.5.1) this issue to an extent:

> Remix 1P
> - Giga Bowser CPU lvl reduced on Very Easy, Easy and Normal

On the other hand, the AI is buffed by another fix:

> [FEATURES]
>
> Fixed "Improved AI" so CPUs Z-Cancel properly
