### ISSUE TITLE
Smash Remix 1.5.1 Giga Bowser Bug

### ISSUE THREAD

**Issue by NewRetro7** [JSsixtyfour/smashremix#175]
Hello, I've recently encountered a potential bug that freezes the game every time you try to
select Giga Bowser from the character select screen. It's a bug encountered in the most recent version of Smash Remix (ver 1.5.1), I have used two different emulators (Parallel 64 and MuppenPlus 64-Next) but the problem persist.

![Bug](https://github.com/JSsixtyfour/smashremix/assets/166312718/4b686007-d0cc-4ad3-8bbb-fdd2fff3cbf0)

**Comment by Santiii733** [comment]
Yes, the problem affects at real hardware too

**Comment by fdalmard** [comment]
I have the same bug. When I hover over the "Bowser" icon and press "up" on the D-pad, the game freezes

I also reproduce the bug when hovering over the "Kirby" icon, press "up" (the icon changes to "Mad piano") then move the "choose character" icon over the "Bowser" icon

**Comment by pring-les** [comment]
Fixed with 1.5.2
