### ISSUE TITLE
Issue with master hand + bonus request..

### ISSUE THREAD

**Issue by TobiasAndUrMom** [JSsixtyfour/smashremix#182]
Master hand crashes the game.
I tried to set master hand and gega bowser against eachother and the game crashed.
I had a similar problem when trying to play as him too.

BONUS REQUEST!
Maybe consider adding rayman in the style of rayman 2 to snash remix..

I have a few ideas for his specials too..

1. An attack where he winds up his punch and he can use he use his fist as a projectile like in the first rayman game but a little less distance as to make it no OP. F-smash.

2. Maybe an attack where he rides the rocket from the second game. Maybe down special.

3. His up special could his helicopter hair to propell him upwards with a hit box overhead with a gentle glide back down. 

4. He should be able to move left and right and fire his power orbs like in rayman 2. Perhaps hold B for a power up shot like in rayman revolution.

5. His up smash could be his victory uppercut animation from reyman 2.

6. His taunt could be the Russian dance he does when completing a level in rayman 2.

7. He could have an idle animation where he bounces his torso like a basket ball like rayman 2.

8. Please make rayman a playable character 🙏

**Comment by pring-les** [comment]
There are no plans to address Master Hand crashes in versus mode. Also, don't request characters here.
