### ISSUE TITLE
Feature Suggestion: Implementing a way to disable the exit button in training mode

### ISSUE THREAD

**Issue by jfrosth** [JSsixtyfour/smashremix#23]
A common occurrence for people who spend a lot of training mode is that they accidentally press exit instead of pressing reset

This can be quite frustrating when you have a complicated set up with the extended training mode options, as it can take a while to set things back up 

Having a way to disable the exit button (at least temporarily) or simply moving the exit button elsewhere could be really useful for people who spend a lot of time in training mode

**Comment by jfrosth** [comment]
This could be done by having exit be done with a button combo, similar to salty runback, having it so that you need to hold down A for the button for it to work. I'm not sure what the easiest/best implementation would be, but I think having any solution to prevent accidental exits would be useful.

**Comment by jtl3d** [comment]
Added in 1.0.0, thanks for the suggestion
