### ISSUE TITLE
Developer Oversights in SSB64

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#24]
SSB64 has 2 hitboxes that never spawn. These were both caused by developer oversights, and they were both very easy to fix.

The first one is Luigi's Dash Attack.
Luigi's dash attack has a final hit that is supposed to spawn on his head and send the opponent away a lot farther than the rest of the hits do.
This doesn't work due to a developer oversight where the command to spawn the hitbox is of the wrong type. It should be a Wait command, but it is instead an After command, which doesn't work.
By switching the type of command to Wait, we can fully restore the hitbox. This require only changing 812F8EF4 from 08000004 to 04000004. ONE BYTE.

The second one is Samus's Up Air.
The final hit of her up air never spawns because of a developer oversight in which there is a total absence of a frame timer altogether.
Re-enabling it by creating a Wait command creates a new, very subtle last hit. If we slown down the footage you'll notice the last hit does 4% instead of 2%, and it causes extra hitstun.
While very subtle, this hitbox gives her a ton of potential for new combos out of Up Air, as it gives just enough extra hitstun to let things like Up Air > Back Air be true combos. It's no longer a completely shitty move.

Transcribed directly from https://www.youtube.com/watch?v=2sa25aojJDs

**Comment by jordanbarkley** [comment]
The original cast will never be modified for any reason. The development team feels strongly about this. 

The claim that this is an oversight is not strong. While I agree the data *could* point to an oversight, there’s no way of knowing how Sakurai intended the move to work. He may have been playing with the possibility you suggested and then gone back on it. He may have updated a C constant to disable to the moves functionality partially.  He may not have seen it but still deemed the move ok. We can’t know. 

What we know is that changing default characters is a very slippery slope that we will avoid.

With love, Jorg

**Comment by leodexe** [comment]
Well, the mod has already extended to a huge advancemente in the new features, characters and stages that before it was thought to be impossible to achieve. I am bringing up this since regional characters have been partially added. But they behave as alts, they don't actually replace the vanilla characters which is a good approach to "avoid the slippery slope of modifying default characters". So it only should be a matter of adding a toggle and present it as a new "feature". Even IF these two characters are permanently fixed as the default characters for new SR releases they STILL are Low Tiers. They wouldn't "break" the current meta or anything similar. Top 5 would still beat the crap out of them and anyways and even so, the worst scenario is that these "fixes" get banned for tournament play, because they aren't part of the game's mechanics canon and Tournament Settings only supports vanilla 64 with any other features that don't modify any sort of the game play such as the physics, mechanics, etc. This is more of a toggleable feature for friendlies or Smash Remix specific tournaments that would allow use of ALL the features the ROM Hack has to offer that would be normally banned in regular Tournament play, such as the new characters and new custom stages for Remix-specific meta.

**Comment by Komotonoto** [comment]
THE GAME IS DEAD UNTIL THEY PATCH VANILLA/SLIPPY64+RANKED+ROLLBACK/REMIX LEGAL TOURNAMENTS

**Comment by leodexe** [comment]
welp, Komotonoto let's make our Smash Remix. These dumb devs are wasting their potential with their dumb ideals about the vanilla cast (which 7/12 are unviable for tournament play), and they feel it's perfectly okay to add a bunch of new characters with better potential than the mid and low tiers leaving almost no reason to play these lame characters other than "nostalgia".

Fuck that shit, let's just make our Smash Remix and revive the scene @Komotonoto 

And obviously Pika/Kirby need to be nerfed, but the vanilla crybabys are not ready for this conversation. They want to keep the game and eternal tier-whore fest rather than buffing everyone and letting other players have fun.

**Comment by Komotonoto** [comment]
TBFHHH. KIDS MADE A WHOLE MOD JUST TO PLAY THE SAME DAMN VANILLA GAME THE REST OF THEIR LIVES 🤣🤣🤣. WHAT A WASTE OF TIME. THEY MADE DLC THAT YOU CANT EVEN USE IN TOURNAMENTS 🤣

**Comment by leodexe** [comment]
> TBFHHH. KIDS MADE A WHOLE MOD JUST TO PLAY THE SAME DAMN VANILLA GAME THE REST OF THEIR LIVES 🤣🤣🤣. WHAT A WASTE OF TIME. THEY MADE DLC THAT YOU CANT EVEN USE IN TOURNAMENTS 🤣
> 
> Let me know how I can help 😌👌

Yeah sure, Mad Piano and the clone wars characters are cool concepts (some not as cool because they feel like totally wasted copy+paste character slots), but what's the point of wasting time developing characters if they're gonna be tournament banned anyways.

Not sure how we can make a mod ourselves, I barely know how to hex-edit gameshark codes, we would first need to find another dev team that agrees with us so we can begin a new mod in the first place.

**Comment by Komotonoto** [comment]
> > TBFHHH. KIDS MADE A WHOLE MOD JUST TO PLAY THE SAME DAMN VANILLA GAME THE REST OF THEIR LIVES 🤣🤣🤣. WHAT A WASTE OF TIME. THEY MADE DLC THAT YOU CANT EVEN USE IN TOURNAMENTS 🤣
> > Let me know how I can help 😌👌
> 
> Yeah sure, Mad Piano and the clone wars characters are cool concepts (some not as cool because they feel like totally wasted copy+paste character slots), but what's the point of wasting time developing characters if they're gonna be tournament banned anyways.
> 
> Not sure how we can make a mod ourselves, I barely know how to hex-edit gameshark codes, we would first need to find another dev team that agrees with us so we can begin a new mod in the first place.

LMK BROTHERRRRR

**Comment by leodexe** [comment]
> > > TBFHHH. KIDS MADE A WHOLE MOD JUST TO PLAY THE SAME DAMN VANILLA GAME THE REST OF THEIR LIVES 🤣🤣🤣. WHAT A WASTE OF TIME. THEY MADE DLC THAT YOU CANT EVEN USE IN TOURNAMENTS 🤣
> > > Let me know how I can help 😌👌
> > 
> > 
> > Yeah sure, Mad Piano and the clone wars characters are cool concepts (some not as cool because they feel like totally wasted copy+paste character slots), but what's the point of wasting time developing characters if they're gonna be tournament banned anyways.
> > Not sure how we can make a mod ourselves, I barely know how to hex-edit gameshark codes, we would first need to find another dev team that agrees with us so we can begin a new mod in the first place.
> 
> LMK BROTHERRRRR

can u follow me on twitter, I don't find ur discord user so I thought we could chat there to discuss some Remix

**Comment by Komotonoto** [comment]
Can't find you either on Twitter. My discord = Komotonoto#2397. My Twitter https://twitter.com/komotonoto
