### ISSUE TITLE
Inconsistency with Metal Mario Regular Fall Speed and Fast Fall Speed might be a developer oversight

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#26]
Okay this was supposed to be a issue to suggest new optional features, but instead I will elaborate a long thread regarding Metal Mario's Fall Speed Data and why it's inconsistent with the chart.

Let's begin by taking a look at the entire frame data chart.
https://nickthename.github.io/ssbframedata/images/charpropertieschart.jpg
![imagen](https://user-images.githubusercontent.com/24327014/81957821-1fac8d80-95db-11ea-8700-b85494564ff9.png)
At first glance every number there seems to be in the right place and makes sense, except for these two that break the pattern:
![imagen](https://user-images.githubusercontent.com/24327014/82093797-d25b1980-96c9-11ea-9bb3-46004869ce18.png)
These are, Metal Mario's Maximum Falling Speed, which is actually higher than his Maximum Fast Fall Speed, you can note many things, one is that Giant DK doesn't follow this pattern and instead he has a Maximum Falling Speed that is actually lower than his Maximum Fast Fall Speed, just like the other 12 playable characters do.

These numbers can led to the idea this was a developer oversight, but why leave it just here?
Well, for one thing, Metal Mario wasn' intended to be playable, just like Giant DK, but that doesn't mean this can't be fixed.

In theory this means that Metal Mario has a Standard Fall Speed that equals to Giant DK's Maximum Fall Speed, which both have values of 100. This also means that Metal Mario's Maximum Fast Fall Speed is near even next to Giant DK Standard Fall Speed. This... just doesn't make sense.

In the practice this means Metal Mario falls at the same maximum speed as Giant DK's Maximum Fast Fall Speed. So shouldn't DK have higher values on his Fall Speed stats to compensate this?

I have done several tests with the purpose of comparing data between Smash 64 mechanics regarding Metal Mario and Giant Donkey Kong, and, in this example, Smash Melee, using Mario with a Metal Box and Donkey Kong with a Super Mushroom to simulate Metal Mario and Giant DK from Smash 64, to find out how much similar or different these characters different fall speeds work.

Starting with Smash 64 on Duel Zone (aka Battlefield), walking off on any of the main stage edges, counting the 1st frame the character is airborne till it touches the lower blast zone, these characters rank in these order:

1st in reaching the lower blast zone: Giant DK (44 frames), fastfalling
2nd: Metal Mario (53 frames), without fastfalling
3rd: Metal Mario (ties with Giant DK at 68 frames) with fast fall executed at frame 15 of being airborne, **NOTE:** this is to compensate the fact that when you fastfall since frame one, he will reach his maximum fast fall speed faster, but if you input the fast fall near the frames 11-19 of being airborne, he will fall slower (≤ 70) until that point. After frame 20 and onwards, he gains a notable fall speed increase greater than 70.
3rd: Giant DK (ties with Metal Mario at 68 frames), without fastfalling.
4th: DK (50 frames), fastfalling
5th: Mario (62 frames), fastfalling
6th: DK (84 frames), without fastfalling
7th and last to reach lower blastzone: Mario (106 frames), without fastfalling

Now the same method is applied with Melee, the stage used is Battlefield, their rank is:

1st to reach lower blastzone: DK (with Super Mushroom + Fast Fall), 25 frames.
2nd: Mario (with Metal Box + Fast Fall) 26 frames.
3rd: DK (Fast Fall) 38 frames.
4th: DK (with Super Mushroom) 41 frames.
5th: Mario (with Metal Box) 42 frames.
6th: Mario (Fast Fall) 50 frames.
7th: DK (without fastfall) 57 frames.
8th: Mario (without fastfall) 74 frames.

It must be noted that fastfalls weren't frame perfect, at least they are off by 1 frame.
Now, this data comparing each game's and character mechanics show some interesting things.

The first thing to note, is that Metal Mario's Fall Speed when he is not fastfalling is close to Giant DK when he fastfalls, but fastfaller DK falls slightly faster than non-fastfalling Metal Mario by a small margin even thought both have values of 100. This can led to the idea that Devs programmed Giant DK and Metal Mario to have the same Fall Speed Values, if not the same by a negligible margin (70 vs 72 in standard fall, 100.1 vs 100.2 in fast fall) both on regular fall and fast fall.

The second thing, is that in Smash Melee, Mario with the Metal Box and DK with the Super Mushroom, both to simulate Metal Mario and Giant DK in Smash 64, their gap is even closer, they barely have one frame of difference in reaching the blast zone. And their regular and fast fall speeds are also close, if not equal by one frame. This might indicated this pattern was highly likely to be the same held true for Smash 64. 

Why make a Fast Fall that is slower than a Regular Fall?
This defeats the purpose of the Fast Fall.

The only explanation is that this was a huge mistake and devs didn't care because anyways Metal Mario wasn't supposed to be a playable character, but now he is.
Instead, if Metal Mario had his Fast Fall Speed normalized, the chart then again would make sense.

It is also worth pointing out that Metal Mario's Body Size Multiplier is based on the Japanese Mario (Body=1), unlike International Mario that his Body Size Multiplier has Body=1.12, so this means Metal Mario has also inherited the Frame Data, Moveset Properties and Hitboxes from Japanese Mario? Anyways, this doesn't explain the Fall Speed inconsistency.

The solution is as simple as reversing these two stats, so Metal Mario begins with a standard Fall Speed of 72, and Fast Falls at maximum of 100. This way he can now have a functional Fast Fall and a Standard Fall that isn't excessive for his weight class (compared to Giant DK's Standard Fall of 72). A permanent change should be the optimal idea, but if you don't feel about permanently modifying it, then a toggle to have both fall speeds vanilla and fixed could be temporarily added. Since he's not part of the original playable cast and he isn't demanded as much as other custom characters such, there shouldn't be any problem if you were to address this issue. Thanks for taking your time reading this long post.

**Comment by JSsixtyfour** [comment]
He's an original character (regardless of normally being accessible to the player or not), which we don't modify. We will not make this change. Developer oversights are left in.

**Comment by leodexe** [comment]
@JSsixtyfour 
You don't have to permanently change it.
You could just add a toggle like pressing right on the dpad in the CSS selection screen since that spot  is unused for Mario and make Metal Mario with Fall Speed and Fast Fall Speed values being inverted.
That way the player can elect to play with vanilla or fixed fall speed Metal Mario.
In fact, this implies making a custom character based on Metal Mario, not modyfing the original Metal Mario (which is more or less the point of adding new chars in the mod), and present it as a new feature.
