### ISSUE TITLE
Bad AI behavior in Cool, Cool Mountain

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#28]
They don't attempt to recover, even if no one hits them and they drop off the platform by themselves.
https://youtu.be/bqHxUKcaN_k

**Comment by JSsixtyfour** [comment]
The AI doesn't work well with custom stages and is not a focus of the mod.

**Comment by leodexe** [comment]
FYI, the AI does play well every custom stage except this one. This behavior is nothing you will see in any other custom stage because it messes up with their usual pattern, and why it isn't a primary goal of the mod? The AI isn't very developed in this game but at least it does what is expected to do, it could use more improvement if for example you eliminate their roll habits so they no longer roll endlessly whenever they are close to the opponent.
