### ISSUE TITLE
Graphical Issues on PJ64

### ISSUE THREAD

**Issue by nexroad** [JSsixtyfour/smashremix#29]
When I play the game, 2D textures such as Shield, items, and Samus’s lasers are either incredibly small, or don’t show up altogether.
![image](https://user-images.githubusercontent.com/66520936/83945237-66a33280-a7d7-11ea-8374-54fb485e2518.jpg)
Is there any way to solve this?

**Comment by jtl3d** [comment]
Use a different video plugin liken GlideN64 4.0.
