### ISSUE TITLE
Suggestion : 4:3 HUD or 16:9 HUD

### ISSUE THREAD

**Issue by Catarax** [JSsixtyfour/smashremix#31]
On RetroArch Mupen64Plus-Next OpenGL 2.0, I can manage to run the game with proper 4:3 HUD however the left/right widescreen borders cut the character (of course) and the in-game widescreen hack adds a bigger fov to it.

So i'm asking for a 4:3 HUD option or a widescreen HUD if possible?

Thank you !

![Screenshot_1](https://user-images.githubusercontent.com/3964507/84609187-3aae3e00-aeb6-11ea-8b6d-6a7c85e20d24.png)

**Comment by jtl3d** [comment]
What would you change in a widescreen HUD?

**Comment by Catarax** [comment]
A widescreen HUD would have the unstretched timer to the top right from my screenshot. 
Like the modern games.

The bottom bar of lives % is also very big when it's stretched.

**Comment by JSsixtyfour** [comment]
Unlikely addition, but noted.

**Comment by Catarax** [comment]
Gamemasterplc just released a new version of his widescreen hack :
https://www.youtube.com/watch?v=gxWloBhzl0E
