### ISSUE TITLE
Patching with the most recent patch

### ISSUE THREAD

**Issue by Rorwig123** [JSsixtyfour/smashremix#32]
Good afternoon,

I read about this patch the other day and decided to give it a try. I have a reliable ROM, but when I drag it onto the windows-drag-here.bat or manually patch it through xdealtUI.exe, I get a dialogue box that looks like this: [https://imgur.com/a/kaBbGtI](url). Any help would be appreciated!

**Comment by jtl3d** [comment]
Did you set your emulator to 8mb?

**Comment by Rorwig123** [comment]
In my ROM directory, it says "Bad ROM? Use GoodN64 & check that RDB is up-to-date." How do I do that?

**Comment by jtl3d** [comment]
Check the readme in the release

**Comment by Rorwig123** [comment]
The readme only mentions steps for Netplay and how to patch the original ROM on multiple OS. The others are in another language and one patch notes.

**Comment by jtl3d** [comment]
Add the rdb anyway and press f5

**Comment by Rorwig123** [comment]
It works now, thank you! Do you know if this would work on an Android emulator?

**Comment by jtl3d** [comment]
No prob. Some stuff may not work on android emulators since we don't support them. Our main focus is console and pj64 for netplay.
