### ISSUE TITLE
Suggestion: Update Readme and Leame to include additional information

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#33]
The information provided in the Readme.txt and Leame.txt could be improved, to show additional instructions for Mupen64Plus on how to add the Smash Remix ROM to the Good ROM database, so you don't have to manually search for the ROM if you already have a chosen ROM directory (in the case of m64py), the ROM won't show up until you manually add it to the mupen64plus.ini ROM database. Here are the steps you could include in order to do so:

---Mupen64Plus
(Optional) If you want the ROM to properly appear in your Mupen64Plus frontend (i.e. m64py)
Good ROM known database, copy this text entry and paste it into your current mupen64plus.ini:

[03C71C0F7AD7127A1AB216FCC99EF46F]
GoodName=SmashRemix0.9.3c
CRC=40D195A0 8CA46F23
Status=3
SaveType=SRAM
Players=4
Rumble=Yes
CountPerOp=1

In m64py for Windows, this file is usually inside the folder "C:\Program Files (x86)\M64Py"
If you use other frontend, you can try searching the mupen64plus.ini file in the same folder where it is the frontend executable.
In Linux, this file is usually inside the user folder "/home/your-username/.config/mupen64plus", thought this may change with the distro.
This step isn't needed as mupen64plus already runs properly the ROM Hack, only that it will add the
ROM to the Good ROM compatible database, so you don't have to manually search for it each time."

The "CountPerOp" line is the Mupen64Plus equivalent to Project64's "Counter Factor" option.

Also, don't add the "ViRefresh=2200" line to mupen64plus.ini, because mupen64plus uses a different method that automatically calculates the VI refresh rate for the game its running to guarantee stable framerate while keeping optimal performance, so no overclocking is needed.

One more thing, while the Leame translation to Spanish is understandable to read, it has slight grammar errors and is somewhat redundant, if you feel like it you could use this Spanish translation provided by me below, which describes the steps more crearly with less redundancy. Also including the instructions to add Smash Remix to Mupen64Plus's Good ROM database in Spanish.

---Spanish
Arrastra tu ROM hacia el programa que corresponda con tu sistema operativo, se generará un nuevo ROM de Smash Remix
en la carpeta de salida (output).

Si quieres jugar con este ROM en Netplay debes copiar el archivo project64.rdb que viene incluido con el parche
hacia tu carpeta de Project64, o copia y pega esta entrada de texto en tu archivo de project64.rdb dentro de tu
carpeta de Project64:

[40D195A0-8CA46F23-C:45]
Good Name=SmashRemix0.9.3c
Internal Name=SmashRemix
Status=Compatible
Counter Factor=1
Culling=1
SMM-Cache=0
SMM-FUNC=0
SMM-TLB=0
RDRAM Size=8
ViRefresh=2200

(Opcional) Si quieres que la ROM aparezca dentro de la lista de ROMs conocidas de tu frontend de Mupen64Plus
(por ejemplo m64py) puedes copiar y pegar la siguiente entrada en el archivo de texto de tu "mupen64plus.ini"

[03C71C0F7AD7127A1AB216FCC99EF46F]
GoodName=SmashRemix0.9.3c
CRC=40D195A0 8CA46F23
Status=3
SaveType=SRAM
Players=4
Rumble=Yes
CountPerOp=1

En m64py para Windows, el mupen64plus.ini usualmente se encuentra dentro de la carpeta "C:\Program Files (x86)\M64Py"
Si usas otro frontend, puedes buscar el mupen64plus.ini en la misma carpeta donde se encuentra el ejecutable del frontend
En Linux, este archivo suele encontrarse en la carpeta de "/home/tu-username/.config/mupen64plus", aunque esto puede variar con la distro.
No es necesario hacer esto porque mupen64plus ya corre bien el juego, solo que de este modo agregará el ROM Hack a la lista
de juegos compatibles reconocidos en la base de datos, por lo que no haría falta que tengas que buscar tu ROM manualmente.

La línea "CountPerOp" es el equivalente de Mupen64Plus al "Counter Factor" de Project64.

Algo más, no intentes añadir la línea "ViRefresh=2200" a mupen64plus.ini, porque Mupen64Plus utiliza otro método diferente para calcular automáticamente la tasa de refresco VI que necesita el juego para mantener el framerate mientras garantiza un rendimiento óptimo, por lo que no hace falta hacer este overclock.

Sigue las instrucciones indicadas por el programa si el generador de ROM falla.

Si el problema persiste después de seguir las instrucciones, utiliza el Delta UI, sigue estas instrucciones:

Paso 1: Asegúrate de tener un ROM legal, original y sin alterar de Super Smash Bros, que sea .z64
(.n64 y .v64 no funcionarán). Puedes convertir fácilmente uno de estos archivos a .z64 usando la herramienta Tool64 (descargar aquí: https://www.zophar.net/utilities/n64aud/tool-n64.html )
Una vez realizado el proceso, verifica que la conversión fue exitosa abriendo el nuevo archivo en Tool64, la extensión debe decir ".z64", y en Byte Order debe decir "Big Endian".

Paso 2: En el cuadro "Source File" haz clic en el botón "Open", luego selecciona el archivo de origen el cual debe ser el ROM que revisaste en el paso 1.
(asegúrate de que el formato sea .z64)

Paso 3: En el cuadro "Patch" haz clic en el botón "Open", selecciona la versión mas reciente de "smashremix0.9.3c.xdelta" (en la carpeta de patches)

Paso 4: En el cuadro "Output File", haz clic en el botón "Open" y selecciona un nombre para el archivo de salida que termine en .z64

Paso 5: haz clic en el botón "Patch". Ahora deberías tener una copia funcional de Smash Remix.

USUARIOS DE ANDROID:

También tienes que hacer el delta patch. Hay delta patches disponible para Android.

USUARIOS DE iOS:

Puedes utilizar la herramienta de parcheo basada en la web en el siguiente enlace:
https://hack64.net/tools/patcher.php
---

An example with Mario Kart 64 (U) [!] would be...
![mariokart64goodrom](https://user-images.githubusercontent.com/24327014/86187639-45014680-bb0a-11ea-9958-e61b0ec64460.png)

Before adding the entry to the .ini file the ROM displays as unknown and the game doesn't appear on the list.
![smashremixunknownrom](https://user-images.githubusercontent.com/24327014/86187643-46cb0a00-bb0a-11ea-9ad0-9b6448316913.png)

After adding the entry to the .ini file the ROM shows properly and it appears on your specified ROM directory list.
![smashremixgoodrom](https://user-images.githubusercontent.com/24327014/86187642-46327380-bb0a-11ea-8b26-eef3d985c4f0.png)

For future releases of Smash Remix, and any other ROM Hack, in order to add it to manually add it to Mupen64Plus database you just have to click on ROM info after loading the game, copy the info and paste the accordingly Good Name, MD5 checksum and CRC1 & CRC2. Internal Name is shown automatically. Using m64py as an example, it may differ with differents frontends.

**Comment by JSsixtyfour** [comment]
Thanks for your suggestions, where is the 

[03C71C0F7AD7127A1AB216FCC99EF46F] pulled from?

**Comment by leodexe** [comment]
> 
> 
> Thanks for your suggestions, where is the
> 
> [03C71C0F7AD7127A1AB216FCC99EF46F] pulled from?
That MD5 I got it from m64py, but any emulator should be able to show the MD5 of the current ROM you are playing.
Here are the steps:
1. Open m64py and click on File > Open ROM > Manually
2. Select and load Smash Remix
3. Now that the game is loaded,  click on File > Show ROM Info
You should see a window titled "ROM Information" like the earlier example, There it will show MD5, CRC1 & CRC2, and all other stuff. That MD5 corresponds to Smash Remix 0.9.3c, other versions of Smash Remix will yield different MD5 and CRCs.

**Comment by leodexe** [comment]
> 
> 
> Thanks for your suggestions, where is the
> 
> [03C71C0F7AD7127A1AB216FCC99EF46F] pulled from?

That MD5 I got it from m64py, but any emulator should be able to show the MD5 of the current ROM you are playing.
Here are the steps:

1. Open m64py and click on File > Open ROM > Manually
2. Select and load Smash Remix
3. Now that the game is loaded, click on File > Show ROM Info

You should see a window titled "ROM Information" like the one in the earlier example, There it will show MD5, CRC1 & CRC2, and all other stuff. That MD5 corresponds to Smash Remix 0.9.3c, other versions of Smash Remix will yield different MD5 and CRCs.

**Comment by JSsixtyfour** [comment]
Yes, thank you. That much I understood. I meant more like where in the ROM. It seems to be some sort of encrypted or other format from within the ROM.  I wanted to see if it was easy if enough to draw from the ROM itself, but this seems easy enough, despite not really being a mupen user.
