### ISSUE TITLE
Mac OSX Catalina compatibility?

### ISSUE THREAD

**Issue by smallMacDonald** [JSsixtyfour/smashremix#35]
Sorry if this is a dumb question.

I've been having some trouble with implementing the Smash Remix patch, as the osx-drag-here program isn't working for me. I have tried to troubleshoot as best as I can, with my very limited knowledge, and I am pretty sure that the downloading and unzipping process is fine, and I have the correct .z64 ROM file type. 

Usually, when downloading software, the Apple permissions will show up in System Preferences, as discussed in the README.txt, but my computer doesn't seem to recognize it enough to give me that permission issue, and gives me this error message instead. 

<img width="532" alt="osx-patcher-message" src="https://user-images.githubusercontent.com/68802503/88473660-8c45e180-ced4-11ea-9a1c-1a69e135ea66.png">

This is speculation at this point, but my current guess is that this is because I am currently running Catalina 10.15.6, and 32-bit applications aren't supported. I don't know enough to check what the osx-drag-here app is using, but this is my best guess at the moment? If this is the case, then I think this also makes the workarounds necessary to run the Windows and Linux versions less feasible. (I might be completely wrong on this)

Are there any current plans to update the osx patcher to 64-bit? 

Do I just have to find a way back to using Mojave, so I can run 32-bit, and, in theory, the osx patcher, to play Smash Remix?

Is there something else that I am overlooking, or some other small piece that I don't know about that might fix stuff? 

Thank you!

**Comment by jtl3d** [comment]
Patch using this site: https://www.romhacking.net/patch/

You're not the first person with this issue but idk when we will look into it.
