### ISSUE TITLE
Gracias

### ISSUE THREAD

**Issue by vickthoor13** [JSsixtyfour/smashremix#37]
Hacen un excelente juego ustedes son geniales!! Muchas gracias pero no sé cómo donarles dinero deberian hacer un vídeo explicándolo pero bueno ojalá sigan así!!

**Comment by gh0sti** [comment]
8. Can I donate to the project? 
No, we do not accept donations or payment of any kind. This non-profit project is a labor of love by the team with the educational purpose of showing people the inner workings of classic games and teaching people how to perform rudimentary code  and game development. All of our work is open source and available for all to analyze and learn from in conjunction with our tutorials. We appreciate the thought though!

sorry for the spanish translator.
8. ¿Puedo donar al proyecto?
No, no aceptamos donaciones ni pago de ningún tipo. Este proyecto sin fines de lucro es un trabajo de amor por parte del equipo con el propósito educativo de mostrar a las personas el funcionamiento interno de los juegos clásicos y enseñar a las personas cómo realizar un código rudimentario y el desarrollo de juegos. Todo nuestro trabajo es de código abierto y está disponible para que todos lo analicen y aprendan junto con nuestros tutoriales. ¡Sin embargo, apreciamos la idea!

**Comment by JSsixtyfour** [comment]
Thank you, but we do not accept donations.
