### ISSUE TITLE
Don't be discouraging

### ISSUE THREAD

**Issue by GeoffreyGamaya** [JSsixtyfour/smashremix#4]
https://github.com/JSsixtyfour/smashremix/blob/168185f9f369c38783260f3cf828ce49954d2869/readme.txt#L1

A lot of young people will probably see this message. It can be very discouraging for them to start to learn programming. And it's always good to get interested in the code, no matter which one it is. You can simply say : 

TO DOWNLOAD LATEST EXECUTABLE VERSION  CLICK ON THE [RELEASES](https://github.com/JSsixtyfour/smashremix/releases) TAB.

**Comment by MaximusChia** [comment]
Sure they dont like competence ^^
