### ISSUE TITLE
Invisible Shields and Tiny Projectiles

### ISSUE THREAD

**Issue by trevorhall2003** [JSsixtyfour/smashremix#42]
I am not sure if this is just on my computer or if it happens to everyone, but I've noticed that while I'm playing, if a character uses their shield, it's invisible but it still works like normal. I also noticed that projectiles such as fireballs and Ness' PK Fire are extremely small. Everything functions as normal it's just I have noticed these small things

**Comment by jordanbarkley** [comment]
This issue is not related to Smash Remix; it's a graphic plugin issue. I'd be more than happy to help you on the Smash Remix Discord (@Cyjorg#1065, https://discord.gg/WMqpeY ) or on Twitter (@cyjorg).
