### ISSUE TITLE
Smash Remix 0.9.4 not working on ED 64 Plus, even with expansion pack.

### ISSUE THREAD

**Issue by Jayr006** [JSsixtyfour/smashremix#46]
I am trying to put smash remix 0.9.4 on my ED 64 Plus, but it is not working, even with the expansion pack on it. 

The smash remix 0.9.3b did work fine.

I've tried all the patches and I still get a black screen on it.

**Comment by jtl3d** [comment]
I have an ED64 Plus and it works fine. Try repatching maybe?

**Comment by Jayr006** [comment]
You mean repatching the already patched rom or patching the original rom again?

**Comment by jtl3d** [comment]
Always patch the original ROM

**Comment by jtl3d** [comment]
If you are still having issues join the discord and someone can help you out. Closing this.
