### ISSUE TITLE
Don't put binaries in the source tree

### ISSUE THREAD

**Issue by easyaspi314** [JSsixtyfour/smashremix#5]
All of the .exes in the tree are open source projects AFAIK.

Therefore, they should either be linked as submodules or listed as a prerequisite.

This is more fair to people who are not on Windows. 

Additionally, the images should be PNGs and models should probably have a format that isn't .bin. This makes editing easier.

**Comment by JSsixtyfour** [comment]
Do you have recommended changes to push? PNGs will not be used as they do not work with our system. I'm all for being inclusive of non-Windows users, but I am not dying to burn time on the matter. If you have recommended changes to push, that's another story.

**Comment by easyaspi314** [comment]
PNGs didn't stop pokeruby…

I could hack together a tool to convert PNGs to rgba5551, if you just tell me the format (assuming raw blobs?).

I am working on non-Windows right now, but I am having an issue with either the source code or https://github.com/ARM9/bass HEAD.

Currently am building on Termux aarch64 btw, and can't get MIDI.asm to assemble.

```
error: malformed expression: read32 MUSIC_TABLE, "../roms/original.z64", 0x3D768
./src/MIDI.asm:13:1: read32 MUSIC_TABLE, "../roms/original.z64", 0x3D768
bass: assembly failed
```

I can't build, is that expected?

original.z64 with the applied patch has the SHA1 9bd78d50dd1b988ac3258daa0fff422f6a65827a, correct?

**Comment by JSsixtyfour** [comment]
So what images are you having issue with? Our textures in the texture folder which are all rgba5551?

As a Windows only user I cannot provide much insight on your situation. The current source should assemble. Cyjorg is a non-Windows user and can potentially provide you with some advice. He's also the creator of our rgba5551 converter. Do you have discord? It may be easier to deal with this issue there.

**Comment by easyaspi314** [comment]
Yes, I have Discord.

**Comment by JSsixtyfour** [comment]
Feel free to visit us if you like some help with things. https://discord.gg/Za23kc5
