### ISSUE TITLE
the darker and lighter tones (shades) of the characters, does not work on the computer.

### ISSUE THREAD

**Issue by pedro020202** [JSsixtyfour/smashremix#51]
the darker and lighter tones (shades) of the characters, it works on the cell phone but not on the computer, what would be the problem?

**Comment by jtl3d** [comment]
Probably graphics plugin

**Comment by pedro020202** [comment]
![Releases · JSsixtyfour_smashremix - Google Chrome 04_12_2020 03_23_48 p  m  (2)](https://user-images.githubusercontent.com/74553771/101206524-a0011180-3645-11eb-904f-8fa413d0cfde.png)
open the image and you will see what I mean
