### ISSUE TITLE
it doesn't work on the computer

### ISSUE THREAD

**Issue by pietro0202** [JSsixtyfour/smashremix#53]
it doesn't work on the computer, this option 
![Releases · JSsixtyfour_smashremix - Google Chrome 04_12_2020 03_23_48 p  m  (2)](https://user-images.githubusercontent.com/74553771/101207289-ca9f9a00-3646-11eb-8ed9-7c7909eaee10.png)

**Comment by jtl3d** [comment]
Do you mean the CPU player?

**Comment by pietro0202** [comment]
yes, and neither the 1p, both the cpu and the 1p,

**Comment by jtl3d** [comment]
Must be a graphics plugin issue. Try a different graphics plugin.

**Comment by pietro0202** [comment]
I tried with other emulators and other graphical plugins but it still doesn't work

**Comment by pietro0202** [comment]
an off-topic question, how does this option work?

![Releases · JSsixtyfour_smashremix - Google Chrome 07_12_2020 11_30_11 p  m](https://user-images.githubusercontent.com/74553771/101436659-fcce2780-38e4-11eb-8cc0-f1d349712f84.png)
