### ISSUE TITLE
OSX Big Sur

### ISSUE THREAD

**Issue by joeldenning** [JSsixtyfour/smashremix#54]
I had some difficulty getting remix to patch correctly on osx big sur, but eventually got it to work. Some of these steps already were required for catalina, but some of them are new. I'm putting all the steps in case anyone else comes looking for this:

1. Unzip smash remix by double clicking on it
2. Open Terminal application and run the following (I got it from [this stackoverflow post](https://stackoverflow.com/a/65010167/1958941)):

```sh
cd ~/Downloads/smashremix0.9.5
sudo chmod -R 755 smashremix0.9.5
```
3. Drag vanilla smash bros rom into the smashremix0.9.5 directory. It must be in that directory before attempting to drag it to the `osx-drag-here` or it will fail.
4. Drag vanilla smash bros rom onto `osx-drag-here`. It will give you a popup about how this is from an untrusted developer. Press Cancel.
5. Open System Preferences -> Security. Go to the General tab. Click on the lock to make changes. There should be some text and a button about the osx-drag-here program. Click "Allow Anyway". Now the program will run and the rom will be created.

**Comment by jtl3d** [comment]
Thanks, Joel!
