### ISSUE TITLE
Nitpicking: Congo Jungle should be spelled Kongo Jungle

### ISSUE THREAD

**Issue by limefiasco** [JSsixtyfour/smashremix#56]
Honestly I might come off as a snob here but Congo Jungle should be spelled with a "K" instead of "C" in order to match the original spelling in Donkey Kong Country (as well as in other Smash Bros titles). I play a lot of Donkey Kong on my SNES and it was really jarring seeing "Kongo" spelled the "correct" way. Thank you so much for the wonderful work you do.

**Comment by JSsixtyfour** [comment]
Not how it is in Smash 64.

**Comment by leodexe** [comment]
You know, I can understand your stance as a "original" "purist" who refuse to modify even the slightest detail even if it's for better balance or QoL.

But refusing to fix a "typo", we can hardly call it a typo, in the game context ghost provide this typo makes perfect sense.

It's getting a bit ridiculous imo.

Justin you are better than this. Come on.

**Comment by leodexe** [comment]
You know, I can understand your stance as a "original" "purist" who refuse to modify even the slightest detail even if it's for better balance or QoL sake.

But refusing to fix a "typo", we can hardly call it a typo, in the game context ghost provide this typo makes perfect sense.

It's getting a bit ridiculous imo.

Justin you are better than this. Come on.
