### ISSUE TITLE
xdelta3: target  window checksum mismatch: XD3_ INVALID_INPUT

### ISSUE THREAD

**Issue by EmerSos** [JSsixtyfour/smashremix#58]
When I want to patch my ROM that error in the title comes out. Why?

**Comment by leodexe** [comment]
You are using an invalid ROM format. Make sure it's big-endian, not little endian or byteswapped.

**Comment by EmerSos** [comment]
https://www.iobit.com/es/share-driver-booster.php?id=S1FH53
