### ISSUE TITLE
Frame Counter for Frame Advance

### ISSUE THREAD

**Issue by emptyW64** [JSsixtyfour/smashremix#59]
A display to show how many frames you have advanced since initiating frame advance - starts at 0, counts up for every frame, resets when frame advance has ended

**Comment by jtl3d** [comment]
Can you describe the use case? I have many ideas that may be related.

**Comment by emptyW64** [comment]
It would be used for testing options/frame windows/general info in frame advance. I often find myself counting out frames when using frame advance and this would speed things up a lot.
ie: something simple like finding the number of frames each character is airborne for both short hop and full slant short hop would involve counting out ~40-60+ frames many times, but with a frame counter you could just speed through to the relevant frame.

**Comment by jtl3d** [comment]
I believe this is addressed via action strings and frames. Let me know if not.
