### ISSUE TITLE
Function recommendation

### ISSUE THREAD

**Issue by luisaguirred** [JSsixtyfour/smashremix#64]
As a result of playing several times, players become professional and may get bored playing with the same characters, an interesting function that many fighting games have is a random character selection.

**Comment by Eikki14** [comment]
Hello. Your project is spectacular. I would like Pichu and Cloud to be added to Smash Remix.  I would thank that very much

**Comment by Pablo476** [comment]
That sounds a great idea!

**Comment by erickhyt123** [comment]
It is a great idea, developers please include it, I leave you an example of the idea, thank you very much for your project!
![Sin título-1](https://user-images.githubusercontent.com/83878764/117549695-73409400-b001-11eb-8236-15610a773846.jpg)

**Comment by elxenier44** [comment]
I would like there to be a mode of 8 fighters or if you can not 6 fighters and include king dedede or meta knight please
