### ISSUE TITLE
More games more "toys"

### ISSUE THREAD

**Issue by darkeholy** [JSsixtyfour/smashremix#65]
N64 have a lot of games, and with ter big Nintendo leak of betas even more, but the game have low number of female characters. Só Why not add like a skin...for example Fox - Cristal from Dinossaur Planet \Wolf - One female co pilot from Star Fox2 \ Claire Ada or Sherry from RE2 \ Killer Intinct Gold or Mortal Kombat girls \ Perfect Dark from Samus \ Nádia from 007 \ Jet Force Gemini girl \ Princess Rutto ...Birdo ...just more moe

**Comment by leodexe** [comment]
The title isn't even related to your request and why would this even matter?
