### ISSUE TITLE
Smash remix read me

### ISSUE THREAD

**Issue by YolverAlexander** [JSsixtyfour/smashremix#67]
Everyone on youtube wants the blue hedgehog and peach. 
and I want them to make that dream come true, the others would be very happy.
If you can add more characters? the more fun and popular the game becomes.
If this game becomes very popular. the youtubers are going to make a video of your game.
Smash remix. If you can do it, you will win everyone's heart.
: D I wish you good luck to be able to achieve that important mission to have a good popularity.
Fulfill my dreams that I have dreamed of so much

![mqdefault](https://user-images.githubusercontent.com/84154078/118188080-dcfbdc00-b40d-11eb-90f3-408df5e170f5.jpg)

smash remix I want these characters to come to light in smash remix. Yes?

**Comment by YolverAlexander** [comment]
![mqdefault](https://user-images.githubusercontent.com/84154078/118188727-dae64d00-b40e-11eb-927a-f5d2ea8e1288.jpg)

**Comment by YolverAlexander** [comment]
F

**Comment by Th4tM4t** [comment]
atleast you got one slot correctly
why are their 2 wolves
roy would just be a up pad type char
