### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by DBLJACK** [JSsixtyfour/smashremix#68]
Thank you for all your hard work.  Many people do not understand the extent it takes to create a project like SSBR.  Hours of animations, tweaking, testing, coding, design, communications and dealing with the general public.  You and your team have provided a dream of many SSB fans come true...for free and easy access to download and play; without compensation.  Please ignore all the requests for new content in which you are constantly bombarded (which I am sure you do already).  Continue at your own pace, make the characters that you enjoy, release when you can and again thank you.

Sincerely, 

A lifelong SSB N64 fan

**Comment by jordanbarkley** [comment]
Too reasonable. Thanks @DBLJACK
