### ISSUE TITLE
 Talk about your favorite characters to smash remix to create them.

### ISSUE THREAD

**Issue by YolverAlexander** [JSsixtyfour/smashremix#69]
I hope you create a character from "Among us" to change color they have the color of the impostor
I hope you create a character from "Steve", the character from Minecraft.
I hope you create a character "Doraemon" This character had never thought about it but his attacks are trolls

Can't add more levels of cpu?

![Captura](https://user-images.githubusercontent.com/84154078/118190550-45988800-b411-11eb-8642-5e5d7279ae9e.PNG)

To make it much more difficult I want to say that it is extreme much more extreme

**Comment by Dannoble1592** [comment]
I hope you create Mewtwo from Pokemon and Isabelle from Animal Crossing.

**Comment by YolverAlexander** [comment]
I hope you create the character "Tails" is the same as conker

![Uploading mqdefault.jpg…]()

**Comment by YolverAlexander** [comment]
Have you heard of these characters? You will love them. I'm sure the next update will be on May 25 or 29

**Comment by YolverAlexander** [comment]
Do not get carried away by the pokemon, surely there is another character like "didi kong" or "Peach" or "waluigi" someone else like villain dolls that never die like "Cartoon cat" or "Boshi" something funny or a powerful character ( # don't get carried away by a less popular character)

**Comment by YolverAlexander** [comment]
![images](https://user-images.githubusercontent.com/84154078/118205418-4d1a5a00-b42e-11eb-908d-896136e27cfc.jpg)

**Comment by YolverAlexander** [comment]
![descarga (1)](https://user-images.githubusercontent.com/84154078/118205705-f2353280-b42e-11eb-975c-a2090ace7ff0.jpg)

![images (1)](https://user-images.githubusercontent.com/84154078/118205710-f7927d00-b42e-11eb-9db7-e8aea4fbc31f.jpg)

![descarga](https://user-images.githubusercontent.com/84154078/118205720-fe20f480-b42e-11eb-9b45-d6de98942023.jpg)

![descarga (2)](https://user-images.githubusercontent.com/84154078/118205735-05e09900-b42f-11eb-9ce2-fe2ad6784033.jpg)

**Comment by leodexe** [comment]
Bruh
