### ISSUE TITLE
 Why do you need sonic? in smash remix

### ISSUE THREAD

**Issue by YolverAlexander** [JSsixtyfour/smashremix#72]
Smash remix is ​​made from a nintendo game and the sonic character is from sega, and nintendo is the sega enemy

apart sonic is not the only good character

Which nintendo game wanted sonic?

The smash bros melee and the smash bros crusade

instead of creating it from smash remix it is already from smash bros

**Comment by YolverAlexander** [comment]
I think they don't have to believe sonic if it's sega

**Comment by leodexe** [comment]
Why does this even matter?
