### ISSUE TITLE
 Bowser giga error

### ISSUE THREAD

**Issue by YolverAlexander** [JSsixtyfour/smashremix#74]
When the giant bowser is on bonus 2 of the platform board. in a part when it touches the hot floor it gets bugged

**Comment by YolverAlexander** [comment]
That is true

**Comment by YolverAlexander** [comment]
when Bowser hits the hot floor in the second bonus or bonuses

**Comment by leodexe** [comment]
You need to provide video evidence of what you claim to be Giga Bowser being bugged in BtP2
