### ISSUE TITLE
Giant Donkey kong error

### ISSUE THREAD

**Issue by YolverAlexander** [JSsixtyfour/smashremix#75]
giant Bowser's mistake in the bonus is that he does the same

And if they both touch the floor, the same thing happens

Got delayed jumping and jumping

and the same thing happens

![lag](https://user-images.githubusercontent.com/84154078/119759650-9af38100-be76-11eb-8d27-89f4f19544a7.PNG)

**Comment by leodexe** [comment]
No entiendo qué es lo que quieres decir. Pero supongo que tiene que ver con el stage de los platforms, en este caso, Giga Bowser no tiene un stage special para platforms y comparte el mismo que el de Bowser si mal no recuerdo.
