### ISSUE TITLE
Unknown Error at 1P Remix

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#77]
![imagen](https://user-images.githubusercontent.com/24327014/125181867-09965f00-e1d7-11eb-94b5-84245a4d8ea0.png)

Was playing on 1P Mode with Metal Mario when this Samus Kirby attempts a Up B, I block it then I attempt to shieldgrab but then the game froze. I don't know what could be the cause of this. Also the music still sounds but corrupted and kinda creepy.

Have played many times and this is the first time that happens.

Platform: ED64PLUS (Copy of Everdrive v2)
N64 is stock unmodified.

**Comment by Selvenity** [comment]
Try modifying/modding your N64. May help.

**Comment by Selvenity** [comment]
Or get a copy of Everdrive 64 V3.

**Comment by masterquest91** [comment]
Can you replicate this on 1.5.0?
