### ISSUE TITLE
How do you use on mobile

### ISSUE THREAD

**Issue by 6dyfer** [JSsixtyfour/smashremix#78]

**Comment by leodexe** [comment]
You cannot patch the hack on mobile. You need a desktop comupter and either Windows/Linux/MacOS and follow the instructions in order to patch the ROM.

**Comment by leodexe** [comment]
You cannot patch the hack on mobile. You need a desktop computer and either Windows/Linux/MacOS and follow the instructions in order to patch the ROM.
