### ISSUE TITLE
Edited

### ISSUE THREAD

**Issue by 6dyfer** [JSsixtyfour/smashremix#81]
If you change your character to the opponents character, the costume will be the same.
![Screenshot_20210819-164119](https://user-images.githubusercontent.com/87343220/130141429-d4f51fcc-5a1b-4099-988b-0b75b5925527.png)

**Comment by jtl3d** [comment]
You can control the opponent's costume so this is working as intended. Only thing you cannot control from the custom menu is the shade, but we are unlikely to address that.
