### ISSUE TITLE
Why I get this error when I try to open the rom file "ssb64asm.z64" which gives me after using 'patch.bat'？ 

### ISSUE THREAD

**Issue by nerix13** [JSsixtyfour/smashremix#94]
![issue](https://user-images.githubusercontent.com/56384643/143535275-a7714e88-1ac7-4118-b8f6-407989e6e425.png)

**Comment by jtl3d** [comment]
Make sure you have expansion ram enabled.

**Comment by nerix13** [comment]
i did that, but still appears, is there another thing that i can do?

**Comment by jtl3d** [comment]
Did you create original.z64 with the right rom first?
