### ISSUE TITLE
Suggestion: Request more features for 1P/Training Mode

### ISSUE THREAD

**Issue by leodexe** [JSsixtyfour/smashremix#95]
1. Handicap in Training Mode: Add a handicap value to simulate 1P handicap-based fights such as Metal Mario and Giant DK on 1P Mode and more generally every other fight in Remix 1P Mode.

2. CPU Mode: Crouch, Run, Roll or set it to <CUSTOM> to input a specific move, could be specially useful if you want it to train against a specific move such as frame-perfect Kirby Uptilts.

3. Shield Break Mode: Add a counter OOS option, so one may set the CPU to do something after shieldstun ends.

4.1 Parry Mode: If the CPU is Yoshi, have it shield at the same frame a hitbox comes out.

4.2 Parry Counter OOS: Make the CPU Yoshi do something after a succesful parry (i.e. grab)

5. Remix Board the Platforms: Add this mode in the main menu so you don't have to get past Stage 6 in Remix Mode just to access the RBtP you want to play.

Oh and for some reason, when entering Training Mode on Wii64, the exit option stopped working since this 1.0 release.

Keep up the good work.

**Comment by jtl3d** [comment]
The Hold a to exit training toggle may be on.

Thanks for the suggestions, but no promises ;)

**Comment by leodexe** [comment]
Hey forgot about a very important feature to request, I don't think it needs another issue thread so I'll post it right here.

6. Custom controller configuration (aka button remapping)

Don't know how much feasible is this, but since Brawl this is natively supported, and this is also supported on Melee as of UCF Melee 1.03. It would be nice if also Smash Remix could have this feature as well. One common use would be to remap taunt to one of the C-buttons, which is perfectly legal in the 64 controller guidelines even with non-N64 controllers like Gamecube.
